C
      COMMON /COMTIME/NRDAY,NRHOUR,NRMIN,NRSEC
C
C     NRDAY     - MDB RECEPTION DAY
C     NRHOUR    - MDB RECEPTION HOUR
C     NRMIN     - MDB RECEPTION MINUTE
C     NRSEC     - MDB RECEPTION SECOND
