C
C     'COMBUFF' CONTAINS READ IN AREAS USED BY VARIOUS FILES ,
C     AS WELL AS END-OF-FILE INDICATOR.
C
cpsdec04      COMMON / COMBUFF / IEOF,IOPTS(678),IPARAMS(33000),IPOINTS(128)
      COMMON / COMBUFF / IEOF,IOPTS(678),IPARAMS(50000),IPOINTS(128)
     C                   ,IMPSTA(2000)
C
C
