C
      COMMON /COMTAB/ NTABBTR(JP2),NTABBS(JP2),NTABBRV(JP2),
     1                NTABBDW(JP2)
C	
C     NTABBTR     - TABLE B,  TABLE REFERENCE
C     NTABBS      - TABLE B,  SCALE
C     NTABBRV     - TABLE B,  REFERENCE VALUE
C     NTABBDW     - TABLE B,  DATA WIDTH
C  
