C
C      COMMON *CONF* -  CONFIDENCE CORRECTIONS AND FLAGS
C
C          ICBO   -  CONFIDENCE CORRECTIONS FOR GROSS LIMIT CHECKS
C          ICOCO  -  CONFIDENCE CORRECTIONS FOR INTERNAL CONSISTENCY
C          IFLAG  -  'PASS' AND 'FAIL' COUNTERS AND CONFIDENCE FLAGS
C
      COMMON /CONF/ ICBO,ICOCO,IFLAG
      DIMENSION ICBO (NPOSS,2)
      DIMENSION ICOCO (NCOCO,2)
      DIMENSION IFLAG (NFLENT,NPARAM)
C  
C    --------------------------------------------------------------------
