C
C      COMMON *CONST* -  CONSTANT VALUES FOR QUALITY CONTROL
C
C          IMISS  -  MISSING DATA INDICATOR FOR FLAGS
C          RMISS  -  MISSING DATA INDICATOR FOR PARAMETERS
C          R      -  GAS CONSTANT
C          RG     -  GRAVITY
C          RGAMMA -  LAPSE RATE
C          RCP    -  SPECIFIC HEAT OF DRY AIR
C          RABS   -  CORRECTION FOR ABSOLUTE TEMPERATURE
C          RVAR   -  INDICATOR FOR VARIABLE DIRECTION
C          RLLIM  -  LATITUDE VALUE TO DISTINGUISH AREAS FOR CHECKING
C          ISEASN -  SEASON FOR REPORT (WINTER/SUMMER)
C          IPASS  -  'PASS' INDICATOR
C          IFAIL  -  'FAIL' INDICATOR
C          IEND   -  'END' INDICATOR
C          IUNCH  -  CONFIDENCE FOR UNCHECKED PARAMETER
C          IFIRST -  'FIRST CALL' INDICATOR
C     
      COMMON /CONST/ IMISS,RMISS,R,RG,RGAMMA,RCP,RABS,RVAR,RLLIM,ISEASN,
     X               IPASS,IFAIL,IEND,IUNCH,IFIRST
C
C    ------------------------------------------------------------------------
C 
