C*****************************************************************
C
C     PARAMETERS FOR BIAS CORRECTION
C
C     NSTNBC     NUMBER OF POSSIBLE SONDE ENTRIES IN SONDE LIST
C     NLEVBC     NUMBER OF PRESSURE LEVELS IN ILEVBC
C     NCORBC     NUMBER OF CORRECTION VALUES IN RCORBC TABLE
C     NSONBC     NUMBER OF SONDE TYPES IN RCORBC TABLE
C     YSTIDBC    ARRAY WITH SONDE LIST
C     YDUMMYBC   DUMMY ARRAY
C     YSTYPBC    ARRAY WITH SONDE TYPES
C     YSNAMBC    ARRAY WITH SONDE TYPES
C     ILEVBC     ARRAY WITH PRESSURE LEVELS
C     RCORBC     3DIM ARRAY WITH CORRECTION VALUES
C     SZNBC      ARRAY WITH BIAS CORRECTED GEOP. HEIGHTS
C     LBC        LOGICAL TO STATE IF BIAS COR WAS SUCCESSFUL
C
      PARAMETER (NSTNBC=1200,
     X           NLEVBC=15,
     X           NCORBC=16,
     X           NSONBC=10)
      CHARACTER*5 YSTIDBC(NSTNBC)
      CHARACTER*8 YDUMMYBC
      CHARACTER*10 YSTYPBC(NSTNBC)
      CHARACTER*10 YSNAMBC(NSONBC)
      DIMENSION ILEVBC(NLEVBC),RCORBC(NCORBC,NLEVBC,NSONBC)
      DIMENSION SZNBC(JTEMP)
      LOGICAL LBC
C
C              INITIALISATION
C
      DATA ILEVBC / 100000, 85000, 70000, 50000, 40000,
     X             30000, 25000, 20000, 15000, 10000,
     X              7000,  5000,  3000,  2000,  1000/
C******************************************************************
