C
C                 PARAMETERS FOR SHIP CHECKING
C
C        NTSUBT  =  MAX NUMBER OF BUFR TYPES AND SUBTYPES
C        NENTMAX =  MAX NUMBER OF REPORTS PER RECORD
C        NSPARAM =  MAX NUMBER OF PARAMETERS PER REPORT
C        NSBPW   =  NUMBER OF BITS IN COMPUTER WORD
C        NUNIQ   =  MAX NUMBER OF NON-UNIQUE CALL SIGNS
C        NMSHIZ  =  MAX NUMBER OF SHIP PLATFORM HEIGHTS
C
      PARAMETER (NTSUBT=4,NENTMAX=10,NSPARAM=2,NSBPW=32,NUNIQ=100)
      PARAMETER (NMSHIZ=100)
C
C    ----------------------------------------------------------------------
C
