C
C                 PARAMETERS FOR QUALITY CONTROL
C
C       NAREA = NUMBER OF AREAS FOR CHECKING LIMITS
C       NSEASN= NUMBER OF SEASONS FOR CHECKING LIMITS
C       NLIM  = NUMBER OF MAX OR MIN LIMITS
C       NLEV  = NUMBER OF UPPER AIR LEVELS
C       NFLENT= NUMBER OF ELEMENTS FOR EACH FLAG
C       NCOCO = NUMBER OF CONFIDENCE CORRECTIONS
C       NPARAM= MAX NUMBER OF PARAMETER VALUES IN REPORT
C
      PARAMETER (NAREA=2,  NSEASN=2,  NLIM=2,  NMM=2*NLIM,
     X           NLEV=22,  NPOSS=NLIM+2,  NFLENT=3,  NCOCO=5,
     X           NPARAM=2000)
C      
C    --------------------------------------------------------------------
