      SUBROUTINE DIURNAL(MM,DD,HH,DLAT,DLON,ANGLE)
C
C
      INTEGER MM,DD,HH
      PI=2.0*ASIN(1.0)
      TWOPI=2.0*PI
      RADCON=TWOPI/360.0
C
C*** SINUS OF SOLAR ELEVATION ANGLE WILL BE APPROXIMATED ************
C*** ANTTI LANGE, ECMWF, 25 JULY 1984.                   ************
C
C      YY=YYMMDD/10000
C      MMDD=YYMMDD-YY*10000
C      MM=MMDD/100
C      DD=MMDD-MM*100
      DAY=FLOAT(MM)*30.44+FLOAT(DD)-31.44
      SEASON=TWOPI*(DAY+9.5)/365.25
      COSSSN=COS(SEASON)
      DECL=-RADCON*23.5*COSSSN
      RLAT=RADCON*DLAT
      SINLAT=SIN(RLAT)
      COSLAT=COS(RLAT)
      RLON=RADCON*DLON
      RLHH=TWOPI*HH/24.00+RLON-PI
      COSLHH=COS(RLHH)
      SINE=SIN(DECL)*SINLAT+COS(DECL)*COSLAT*COSLHH
C
      ANGLE = ASIN(SINE) * 180. / PI
C
      RETURN
      END
